name: start-tercen

description: Start a local instance of tercen to run tests

inputs:
  branch:  
    description: 'Tercen image branch'
    required: false
    default: 'stage'

runs:
  using: "composite"
  steps: 
    - name: Pull tercenctl
      run: docker pull tercen/tercenctl:release
      shell: bash
    - run: docker compose -f "docker-compose.yml" up -d
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        TERCEN_IMAGE_TAG: ${{ inputs.branch }}
    - run: |
        chmod +x check-tercen-status.sh
        ./check-tercen-status.sh http://172.42.0.42 5400 
      shell: bash
      working-directory: ${{ github.action_path }}
