name: start-tercen

description: Start a local instance of tercen to run tests

inputs:
  branch:  
    description: 'Tercen image branch'
    required: false
    default: 'stage'

runs:
  using: "composite"
  steps: 
    - run: docker-compose -f "docker-compose.yml" up -d
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        TERCEN_IMAGE_TAG: ${{ inputs.branch }}
    - run: |
        chmod +x wait-for-it.sh
        ./wait-for-it.sh 127.0.0.1:5400 -- echo wait-for-it-done
        sleep 60
      shell: bash
      working-directory: ${{ github.action_path }}
