name: start-tercen

description: Start a local instance of tercen to run tests

runs:
  using: "composite"
  steps: 
    - run: docker-compose -f "docker-compose.yml" up 
      shell: bash
      working-directory: ${{ github.action_path }}

