version: "3.9"

networks:
  tercen:
    ipam:
      driver: default
      config:
        - subnet: 172.42.0.0/16

services:

  couchdb:
    networks:
      tercen:
        aliases:
          - couchdb
    image: ibmcom/couchdb3:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb3-data:/opt/couchdb/data
    restart: always

  tercen:
    networks:
      tercen:
        ipv4_address: 172.42.0.42
        aliases:
          - tercen
    image: tercen/tercen:stage
    ports:
      - 5400:5400
    volumes:
      - /var/lib/tercen/external:/var/lib/tercen/external
      - tercen-data:/var/lib/tercen/data
      - ./config/tercen:/etc/tercen
      - var-run:/var/run
      - tercen-run:/var/lib/tercen/run
      - tmp:/tmp
    environment:
      - TERCEN_CLIENT_URI=http://127.0.0.1:5400
    command: ["/wait-for-it.sh", "127.0.0.1:5400", "--", "echo", "OK"]
    restart: always

  sarno:
    networks:
      tercen:
        aliases:
          - sarno
    image: tercen/sarno:stage
    volumes:
      - tercen-data:/var/lib/tercen/data
      - tercen-run:/var/lib/tercen/run
      - tmp:/tmp
    restart: always

  runtime-docker:
    privileged: true
    image: docker:20.10.9-dind-alpine3.14
    networks:
      tercen:
        aliases:
          - runtime-docker
    volumes:
      - var-run:/var/run
      - var-lib-docker:/var/lib/docker
      - tercen-data:/var/lib/tercen/data
      - /var/lib/tercen/external:/var/lib/tercen/external
      - tmp:/tmp
    restart: always


volumes:
  couchdb3-data:
  tercen-data:
  var-lib-docker:
  var-run:
  tercen-run:
  tmp:
