name: Workflow Stage CI

description: Continuous integration test for workflow templates

inputs:
  git-repository:  
    description: 'Github repository'
    required: true
    default: ''
  branch:  
    description: 'Github repository branch'
    required: false
    default: 'main'
  tag:  
    description: 'Github repository commit or version tag'
    required: false
    default: ''
  git-token:  
    description: 'Github access token'
    required: true
    default: ''
  docker-username:  
    description: 'Docker username'
    required: true
    default: ''
  docker-password:  
    description: 'Docker password'
    required: true
    default: ''
  tercen-username:  
    description: 'Tercen user'
    required: true
    default: ''
  tercen-password:  
    description: 'Tercen password'
    required: true
    default: ''
  tercen-uri:  
    description: 'Tercen operator service URI'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: docker login
      run: |
        docker login --username ${{ inputs.docker-username }} --password ${{ inputs.docker-password }}
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Install Template Runner
      run: | 
        docker pull tercen/workflow_runner:latest
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Test template 
      run: |
        docker run  -t --name=workflow_runner --net=host tercen/workflow_runner:latest \
          --templateRepo=${{ inputs.git-repository }} \
          --user=${{ inputs.tercen-username }} \
          --passw=${{ inputs.tercen-password }} \
          --serviceUri=${{ inputs.tercen-uri }} \
          --gitToken=${{ inputs.git-token }} \
          --report
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: 'Copy Result File'
      if: always()  
      run: docker cp workflow_runner:/operator/test_results.json test_results.json
      shell: bash
      working-directory: ${{ github.action_path }}
    # - name: 'Create Tercen Logs'
    #   if: always()  
    #   run: docker logs  start-tercen_tercen_1 > tercen_logs.log
    #   shell: bash
    #   working-directory: ${{ github.action_path }}
    - name: 'Upload Runner Results'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ${{ github.action_path }}/test_results.json
        retention-days: 7
    # - name: 'Upload Tercen Logs'
    #   if: always()
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: TercenLogs
    #     path: ${{ github.action_path }}/tercen_logs.log
    #     retention-days: 7

      
  

