name: Workflow CI

description: Continuous integration test for workflow templates

inputs:
  git-repository:  
    description: 'Github repository'
    required: true
    default: ''
  branch:  
    description: 'Github repository branch'
    required: false
    default: 'main'
  tag:  
    description: 'Github repository commit or version tag'
    required: false
    default: ''
  git-token:  
    description: 'Github access token'
    required: true
    default: ''
  service-uri:  
    description: 'Service URI'
    required: false
    default: ''
  tercen-username:  
    description: 'Tercen username'
    required: false
    default: ''
  tercen-password:  
    description: 'Tercen password'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: tercen/actions/start-tercen@main
    - name: Log in to the Container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Template Runner
      run: | 
        docker pull tercen/workflow_runner_operator:latest
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Test template 
      run: |
        docker run  -t --name=workflow_runner --net=host tercen/workflow_runner_operator:latest \
          --templateRepo=${{ inputs.git-repository }} \
          --report \
          --user=${{ inputs.tercen-username }} \
          --passw=${{ inputs.tercen-password }} \
          --serviceUri=${{ inputs.service-uri }} \
          --gitToken=${{ inputs.git-token }}
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: 'Copy Result File'
      if: always()  
      run: docker cp workflow_runner:/operator/test_results.json test_results.json
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: 'Create Tercen Logs'
      if: always()  
      run: docker logs  start-tercen_tercen_1 > tercen_logs.log
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: 'Read Runner Results'
      id: json-content
      run: |
        echo "JSON=`cat ${{ github.action_path }}//test_results.json | tr -d '[:space:]'`" >> "$GITHUB_OUTPUT"
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: 'Check Runner Results'
      if: ${{ steps.json-content.outputs.JSON != '{"Status":"Success"}' }}
      run: exit 1
      shell: bash
    - name: 'Upload Runner Results'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: ${{ github.action_path }}/test_results.json
        retention-days: 7
    - name: 'Upload Tercen Logs'
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: TercenLogs
        path: ${{ github.action_path }}/tercen_logs.log
        retention-days: 7

      
  

