name: Workflow Release

description: Release a new template version

inputs:
  git-repository:  
    description: 'Github repository'
    required: true
    default: ''
  branch:  
    description: 'Github repository branch'
    required: false
    default: 'main'
  tag:  
    description: 'Github repository commit or version tag'
    required: false
    default: ''
  git-token:  
    description: 'Github access token'
    required: true
    default: ''
  docker-username:  
    description: 'Docker username'
    required: true
    default: ''
  docker-password:  
    description: 'Docker password'
    required: true
    default: ''
  service-uri:  
    description: 'Service URI'
    required: false
    default: ''
  tercen-user:  
    description: 'Tercen username'
    required: false
    default: 'test'
  tercen-pwd:  
    description: 'Tercen password'
    required: false
    default: 'test'

runs:
  using: "composite"
  steps:
    - uses: tercen/actions/start-tercen@main
    - name: docker login
      run: |
        docker login --username ${{ inputs.docker-username }} --password ${{ inputs.docker-password }}
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Install Template Runner
      run: | 
        docker pull tercen/workflow_runner:latest
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Test template 
      run: |
        docker run  -t --name=workflow_runner --net=host tercen/workflow_runner:latest \
          --templateRepo=${{ inputs.git-repository }} \
          --tag=${{ inputs.tag }} \
          --user=${{ inputs.tercen-user }} \
          --passw=${{ inputs.tercen-pwd }} \
          --serviceUri=${{ inputs.service-uri }} \
          --report \
          --gitToken=${{ inputs.git-token }}
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Create required package.json
      run: echo '{}' > package.json
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Build changelog
      id: Changelog
      uses: tercen/generate-changelog-action@master
    - name: Create release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ inputs.git-token }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: ${{steps.Changelog.outputs.changelog}}
        draft: false
        prerelease: false
