name: MKDocs CI

description: MKDocs with mike

inputs:
  branch:  
    description: 'mkdocs branch'
    required: false
    default: 'gh-pages'
  tag:  
    description: 'doc version'
    required: false
    default: 'latest'
  
runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64      
        cache: 'pip'          
        cache-dependency-path: '${{ github.action_path }}/requirements.txt'
            
    - name: Install Python dependencies
      run: python3 -m pip install -r ${{ github.action_path }}/requirements.txt

    - name: Configure Git user
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
  
    - name: Deploy with mike
      run: |
        git fetch origin ${{ inputs.branch }} --depth=1
        mike deploy --push --branch ${{ inputs.branch }} ${{ inputs.tag }}