name: MKDocs CI

description: MKDocs with mike

inputs:
  branch:  
    description: 'mkdocs branch'
    required: false
    default: 'gh-pages'
  set_default:
    description: 'set as default'
    required: false
    default: 'false'
  tag:  
    description: 'doc version'
    required: false
    default: 'pre-release'
  committers_api_key:
    description: 'github token for MKDOCS_GIT_COMMITTERS_APIKEY'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        architecture: x64      
        # cache: 'pip'          
        # cache-dependency-path: '${{ github.action_path }}/requirements.txt'
            
    - name: Install Python dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: python3 -m pip install -r requirements.txt

    - name: Configure Git user
      shell: bash
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: mike set-default
      shell: bash
      run: |
        mike set-default --allow-undefined ${{ inputs.tag }}
      if: 'true' == ${{ inputs.set_default }}

    - name: Deploy with mike
      shell: bash
      run: |
        export MKDOCS_GIT_COMMITTERS_APIKEY=${{ inputs.committers_api_key }}
        git fetch origin ${{ inputs.branch }} --depth=1
        mike deploy --push --branch ${{ inputs.branch }} ${{ inputs.tag }}